# Generated by Django 5.0.6 on 2024-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id_family', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=70)),
                ('family_code', models.CharField(max_length=5)),
                ('family_members', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
