# Generated by Django 5.0.6 on 2024-07-08 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='management',
            fields=[
                ('id_income', models.AutoField(primary_key=True, serialize=False)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gastos', models.JSONField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
