# Generated by Django 5.0.6 on 2024-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_management_delete_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
