# Generated by Django 5.0.6 on 2024-07-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_management_disponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='management',
        ),
    ]
