# Generated by Django 5.0.6 on 2024-07-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor', '0004_delete_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tipos_gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='management',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponible', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('gastado', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(max_length=30)),
                ('monto_gasto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_gasto', models.DateField()),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.management')),
                ('id_tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.tipos_gasto')),
            ],
        ),
    ]
