# Generated by Django 5.0.6 on 2024-07-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_member_of_family',
        ),
    ]
